services:
  web:
    build: .
    command: python mysite/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings
      - REDIS_URL=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
